language: ruby
before_install:
 - gem update --system
 - gem install bundler
script: bundle exec rake
rvm:
 - 2.4.1
 - jruby-1.7.26
notifications:
  email:
    on_failure: always
    on_success: never
